name: Run bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    name: run bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set API key as environment variable
        env:
          KEY: ${{ secrets.API_KEY }}
      - name: Run main script
        run: python3 main.py
