name: place a bet 

on:
  workflow_dispatch:
  schedule:
    - cron: '5 9 * * *'

jobs:
  build:
    name: place a bet 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: run app
        env:
          KEY: ${{ secrets.API_KEY }}
        run: python3 app.py
